name: Latest YouTube Shorts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-youtube:
    name: Update repo with latest shorts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YTSHORTS
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCD3JyJgFvXZIrkrI_UtDa9w"
